// $("#dropzone").droppable({
//     drop: function (event, ui) {
//         $(this).css('background', 'white');
//     },
//     over: function (event, ui) {
//         $(this).css('background', 'rgb(236, 236, 236)');
//     },
//     out: function (event, ui) {
//         $(this).css('background', 'black');
//     }
// });
// $("#winston").draggable({ containment: "#dropzone" });




$('.element').draggable({
    cursor: 'move',
    revert: true,
    start: function (event, ui) {
        $source = $(this).attr("src");
    }
});

$nb = 1;
var correctCards = 0;

$('#cardPile div div div').droppable({
    hoverClass: 'hovered',
    accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
    drop: handleCardDrop
})


function handleCardDrop(event, ui) {
    var $el = $("<img class='element " + $nb + "' src='" + $source + "' height='100px'>");
    $(this).append($el);
    $(this).droppable('disable');

    $w = $("." + $nb).width();
    $h = $("." + $nb).height();

    $(this).css("width", $w);
    $(this).css("height", $h);
    $(this).css("border", "none");

    correctCards++;
    $nb++;

    if (correctCards == 10) {
        //alert("BRAVOOOOOOOOOOOOOOO!!!!!!!!!!!");
    }

}



$nbrClick = 1;

$('body').on('click', '#ballon', function () {

    if ($nbrClick > 3) {

        alert("Score : " + $score + "\nRecommencer");
    }
    else if ($nbrClick === 1) {
        $score = 0;
        $score += (10 - ($('#cardPile .element').length)) * 3;
        fallElement();
    }
    else if ($nbrClick === 2) {
        $score += (10 - ($('#cardPile .element').length)) * 2;
        fallElement();
    }
    else if ($nbrClick === 3) {
        $score += (10 - ($('#cardPile .element').length));
        fallElement();
    }

    $nbrClick++;
    console.log(10 - ($('#cardPile .element').length));
});

function fallElement() {
    let random = getNbrCan();
    console.log("Nbr de cannette qui tombe : " + random);
    for (let i = 1; i <= random; i++) {
        let random2 = getCan();
        console.log("Canette numéro : " + random2);
        $('.' + random2 + '').css('animation', 'float 0.5s linear');
        setTimeout(function () { $('.' + random2 + '').remove() }, 450);
    }
}

function getNbrCan() {
    var minNumber = 1; // le minimum
    var maxNumber = 10; // le maximum
    var randomnumber = Math.floor(Math.random() * (maxNumber) + minNumber); // la fonction magique
    return randomnumber;
}
function getCan() {
    var minNumber = 1; // le minimum
    var maxNumber = 10 // le maximum
    var randomnumber = Math.floor(Math.random() * (maxNumber) + minNumber); // la fonction magique
    return randomnumber;
}


