$('.element').draggable({
    cursor: 'move',
    revert: true,
    start: function (event, ui) {
        $source = $(this).attr("src");
    }
});

$nb = 1;
var correctCards = 0;

$('#cardPile div div div').droppable({
    hoverClass: 'hovered',
    accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
    drop: handleCardDrop
})


function handleCardDrop(event, ui) {
    var $el = $("<img class='element " + $nb + "' src='" + $source + "' height='100px'>");
    $(this).append($el);
    $(this).droppable('disable');

    $w = $("." + $nb).width();
    $h = $("." + $nb).height();

    $(this).css("width", $w);
    $(this).css("height", $h);
    $(this).css("border", "none");

    correctCards++;
    $nb++;

    if (correctCards == 10) {
        //alert("BRAVOOOOOOOOOOOOOOO!!!!!!!!!!!");
    }

}



$nbrClick = 0;
$score = 0;
$score1 = 0;
$score2 = 0;
$score3 = 0;

$('body').on('click', '#ballon', function () {
    $nbrClick++;
    //console.log(10 - ($('#cardPile .element').length));

    if ($nbrClick > 3) {
        return;
    }
    else if ($nbrClick === 1) {
        fallElement();

        setTimeout(function () {
            $score1 = (10 - ($('#cardPile .element').length)) * 3;
            console.log("Score : " + $score1);
        }, 500);

    }
    else if ($nbrClick === 2) {
        fallElement();
        setTimeout(function () {
            $score2 = ((10 - ($score1 / 3)) - ($('#cardPile .element').length)) * 2;
            console.log("Score : " + $score2);
        }, 500);
    }
    else if ($nbrClick === 3) {
        fallElement();
        setTimeout(function () {
            $score3 = ((10 - (($score1 / 3) + ($score2 / 2))) - ($('#cardPile .element').length));
            $score = $score1 + $score2 + $score3;
            alert("Score : " + $score + "\nRecommencer");
            var game = new Partie("Partie1", $score);
            game.setDate();
            $.ajax({
                type:"POST",
                url: "php/Controller/PrincipalController.php",
                data: "GET=getUser",
                success: function retour(retour) {
                    var retour = JSON.parse(retour);
                    if (retour.user != "" && retour.user != null) {
                        var param = JSON.stringify({
                            x: {
                                'game': game,
                                'name': game.getNom(),
                                'user': retour.user
                            }
                        });
                        $.ajax({
                            type: "POST",
                            url: "php/Controller/PrincipalController.php",
                            data: "POST=postGame&PARAM=" + param,
                            success: function retour2(retour2) {
                                console.log(retour2);
                                retour2 = JSON.parse(retour2);
                                console.log(retour2);
                            }
                        })
                    } else {
                        console.log("coucou");
                        console.log(retour);
                    }
                }
            })
        }, 500);
    }
});

function fallElement() {
    let random = getNbrCan();
    console.log("Nbr de cannette qui tombe : " + random);
    for (let i = 1; i <= random; i++) {
        let random2 = getCan();
        console.log("Canette numéro : " + random2);
        $('.' + random2 + '').css('animation', 'float 0.5s linear');
        setTimeout(function () { $('.' + random2 + '').remove() }, 450);
    }


}

function getNbrCan() {
    var minNumber = 1; // le minimum
    var maxNumber = 10; // le maximum
    var randomnumber = Math.floor(Math.random() * (maxNumber) + minNumber); // la fonction magique
    return randomnumber;
}
function getCan() {
    var minNumber = 1; // le minimum
    var maxNumber = 10 // le maximum
    var randomnumber = Math.floor(Math.random() * (maxNumber) + minNumber); // la fonction magique
    return randomnumber;
}


